security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: bcrypt


    role_hierarchy:
        ROLE_MOD: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_MOD]


    providers:
        fos_userbundle:
           id: fos_user.user_provider.username_email


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true

            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: homepage

            oauth:
                resource_owners:
                    facebook: "/login/check-facebook"
                    google: "/login/check-google"
                login_path: /
                failure_path: /login

                oauth_user_provider:
                    service: custom_user_provider

            logout:
                path: fos_user_security_logout
                target: homepage

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }

