# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
  custom_user_provider.class: AppBundle\Security\UserProvider

services:
    custom_user_provider:
        class: "%custom_user_provider.class%"
        arguments: ['@fos_user.user_manager', {facebook: facebook_id, google: google_id}]